# fly.toml app configuration file for kyozo-api

app = "kyozo-api"
primary_region = "sea"
kill_signal = "SIGTERM"
kill_timeout = "30s"

[experimental]
  auto_rollback = true

[build]
  # Use build secrets for sensitive build-time variables
  # [build.args]
  #   BUILD_SECRET = "secret_value"

[env]
  MIX_ENV = "prod"
  PHX_HOST = "kyozo-api.fly.dev"
  PORT = "4000"
  ECTO_IPV6 = "true"
  ERL_AFLAGS = "-proto_dist inet6_tcp"
  PHX_SERVER = "true"
  RELEASE_DISTRIBUTION = "name"
  RELEASE_NODE = "kyozo@fly-app-kyozo-api.internal"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 10
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "GET"
    timeout = "10s"
    path = "/api/health"
    protocol = "http"
    headers = {}

# Virtual machine configuration
[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Deploy configuration
[deploy]
  release_command = "/app/bin/migrate"
  strategy = "rolling"

# Static file serving
[[statics]]
  guest_path = "/app/lib/kyozo-*/priv/static"
  url_prefix = "/static/"

# Persistent storage
[[mounts]]
  destination = "/app/tmp"
  source = "kyozo_tmp"

[[mounts]]
  destination = "/app/uploads"
  source = "kyozo_uploads"

# Process groups
[processes]
  app = "/app/bin/server"

# Metrics and monitoring
[metrics]
  port = 9091
  path = "/metrics"

# Secrets (configure via fly secrets set)
# DATABASE_URL - PostgreSQL connection string
# SECRET_KEY_BASE - Phoenix secret key base
# LIVE_VIEW_SIGNING_SALT - LiveView signing salt
# GUARDIAN_SECRET_KEY - Guardian JWT secret
# OAUTH_GITHUB_CLIENT_ID - GitHub OAuth client ID
# OAUTH_GITHUB_CLIENT_SECRET - GitHub OAuth client secret
# OAUTH_GOOGLE_CLIENT_ID - Google OAuth client ID
# OAUTH_GOOGLE_CLIENT_SECRET - Google OAuth client secret

# Environment-specific overrides
# Uncomment and modify as needed for different environments
# [[env]]
#   NODE_ENV = "production"
#   LOG_LEVEL = "info"