defmodule Dirup.AI.Providers.Anthropic do
  @behaviour Dirup.AI.Provider

  @impl Dirup.AI.Provider
  def skillsets, do: [:code_generation, :long_context_reasoning]

  @impl Dirup.AI.Provider
  def run_task(:dockerfile_generation, params) do
    # In a real implementation, you would use a library like Req or HTTPoison
    # to call the Anthropic API with the provided params.
    # api_key = Application.get_env(:dirup, __MODULE__)[:api_key]
    IO.puts("Task :dockerfile_generation handled by Anthropic")

    {:ok,
     %{
       provider: __MODULE__,
       content: "# Dockerfile generated by Anthropic...\nFROM elixir:1.15..."
     }}
  end

  def run_task(task_name, _params) do
    {:error, {:unsupported_task_by_provider, task_name, __MODULE__}}
  end
end
