defmodule Kyozo.Repo.Migrations.AddOwnerUserIdToTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_teams) do
      modify :team_id, :uuid, null: true
      modify :user_id, :uuid, null: true
    end
  end

  def down do
    alter table(:user_teams) do
      modify :user_id, :uuid, null: false
      modify :team_id, :uuid, null: false
    end
  end
end
