openapi: 3.1.0
info:
  title: agent.v1
paths: {}
components:
  schemas:
    agent.v1.WebAppConfig:
      type: object
      properties:
        runner:
          type: string
          title: runner
          description: runner is the address of the runner that the application should use.
        reconnect:
          type: boolean
          title: reconnect
          description: Reconnect is a flag to enable automatic reconnecting to the runner.
          nullable: true
        invertedOrder:
          type: boolean
          title: inverted_order
          description: InvertedOrder is a flag to invert the order of the blocks.
          nullable: true
      title: WebAppConfig
      additionalProperties: false
      description: WebAppConfig is the application configuration.
security: []
